/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TMSupervisorRole;

import Business.Enterprise.TrainAuthorityEnterprise;
import Business.TrainManagementSystem.Line;
import Business.TrainManagementSystem.Route;
import Business.TrainManagementSystem.RouteSchedule;
import Business.TrainManagementSystem.Segment;
import Business.TrainManagementSystem.TimeSlot;
import Business.TrainManagementSystem.TimeSlot.TimeSlotRange;
import Business.TrainManagementSystem.Train;
import Business.TrainManagementSystem.TrainSchedule;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Manasi Laddha
 */
public class ManageLineScheduleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageLineScheduleJPanel
     */
    JPanel userProcessContainer;
    TrainAuthorityEnterprise enterprise;
    
    public ManageLineScheduleJPanel(JPanel userProcessContainer,TrainAuthorityEnterprise enterprise) {
        initComponents();
        
        this.userProcessContainer  = userProcessContainer;
        this.enterprise = enterprise;
        
       // populateLinesComboBox();  
        populateNewLinesComboBox();
        populateTrains();
        populateRoute();
        
        lblSubheading.setText("");
        
        tblSearchDetails.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN,18));
        
    }
    
    
    private void populateNewLinesComboBox(){
        
        cboNewLinesSchedules.removeAllItems();
          for(Line l : enterprise.getLineCatalog().getLinesList()){
              if(!l.isIsActive()){
            //if(l.getStartStation() == null || l.getEndStation() == null){                 
                cboNewLinesSchedules.addItem(l);  
            //}
              }
        }    
         
        if(cboNewLinesSchedules.getItemCount() <= 0){    
           cboNewLinesSchedules.setEnabled(false);
           btnCreateSchedule.setEnabled(false);
        }  
        else {
           cboNewLinesSchedules.setEnabled(true);
           btnCreateSchedule.setEnabled(true);  
        }
        
    }
    
    
    private void populateTrains(){
        cboTrains.removeAllItems();
//      for(Line selectedLine : enterprise.getLineCatalog().getLinesList()){
        for(Train t: enterprise.getTrainCatalog().getTrainsList()){
//            if(t.getLineOnTrain() == selectedLine){
                cboTrains.addItem(t);
//            }
         }
//       }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCreateSchedule = new javax.swing.JButton();
        cboNewLinesSchedules = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearchDetails = new javax.swing.JTable();
        cboSearchCriteria = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        btnSearchSchedule = new javax.swing.JButton();
        cboRoutes = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cboTrains = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        lblSubheading = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lineSchedule.png"))); // NOI18N
        jLabel6.setText("Manage Lines Schedule");

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnCreateSchedule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreateSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/schedule.png"))); // NOI18N
        btnCreateSchedule.setText("Create Schedule");
        btnCreateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateScheduleActionPerformed(evt);
            }
        });

        cboNewLinesSchedules.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Line Name :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboNewLinesSchedules, 0, 221, Short.MAX_VALUE))
                .addContainerGap(995, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNewLinesSchedules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(btnCreateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(603, 603, 603))
        );

        jTabbedPane1.addTab("Create Schedule", jPanel1);

        tblSearchDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblSearchDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Train Route", "Train Schedule"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblSearchDetails);

        cboSearchCriteria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSearchCriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Route", "Train" }));
        cboSearchCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSearchCriteriaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Search by:");

        btnSearchSchedule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearchSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/schedule.png"))); // NOI18N
        btnSearchSchedule.setText("Search Schedule");
        btnSearchSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchScheduleActionPerformed(evt);
            }
        });

        cboRoutes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRoutesActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Route :");

        cboTrains.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboTrains.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Train :");

        lblSubheading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubheading.setText("Route : <value>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubheading)
                    .addComponent(btnSearchSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTrains, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(524, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTrains, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(49, 49, 49)
                .addComponent(btnSearchSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblSubheading)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Schedule", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateScheduleActionPerformed
        // TODO add your handling code here:
        Line selectedLine = (Line) cboNewLinesSchedules.getSelectedItem();
        selectedLine.setIsActive(true);
        enterprise.setSchedule(selectedLine);
        cboNewLinesSchedules.removeItem(selectedLine);
        populateNewLinesComboBox();

    }//GEN-LAST:event_btnCreateScheduleActionPerformed

    private void btnSearchScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchScheduleActionPerformed
        // TODO add your handling code here:
        String result = cboSearchCriteria.getSelectedItem().toString();
        if(result.equalsIgnoreCase("Route")){
           
            DefaultTableModel dtm =(DefaultTableModel) tblSearchDetails.getModel();
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            dtm.addColumn("Route Schedule");
            dtm.addColumn("Train Running");
            
            Route selectedRoute =(Route) cboRoutes.getSelectedItem();
            
            lblSubheading.setText("Selected Route : " + selectedRoute.getRouteName());
            
            for(RouteSchedule rs: selectedRoute.getRouteSchedules()){  
                if(rs.isSlotTaken()){
                    Object row[] = new Object[2];
                    row[0] = rs.getTimeSlotsTrain().getValue();
                    row[1] = rs.getTrainOffered().getTrainName();
                    dtm.addRow(row);
                }
            }
            
            
        }
        else if(result.equalsIgnoreCase("Train")){
            
            
            DefaultTableModel dtm =(DefaultTableModel) tblSearchDetails.getModel();
            dtm.setRowCount(0);
            dtm.setColumnCount(0);
            dtm.addColumn("Train Schedule");
            dtm.addColumn("Route");
            
            Train selectedTrain =(Train) cboTrains.getSelectedItem();
            
            lblSubheading.setText("Selected Train : " + selectedTrain.getTrainName());
            
            for(TrainSchedule ts: selectedTrain.getTrainSchedule()){                
                Object row[] = new Object[2];
                row[0] = ts.getTimeSlot().getValue();
                row[1] = ts.getRoute().getRouteName();
                dtm.addRow(row);
            }
            
            
           
        }
    }//GEN-LAST:event_btnSearchScheduleActionPerformed

    private void cboSearchCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSearchCriteriaActionPerformed
        // TODO add your handling code here:
        
        String result = cboSearchCriteria.getSelectedItem().toString();
        if(result.equalsIgnoreCase("Route")){
            cboRoutes.setEnabled(true);
            cboTrains.setEnabled(false);
        }
        else if(result.equalsIgnoreCase("Train")){
            cboRoutes.setEnabled(false);
            cboTrains.setEnabled(true);
        }
        
    }//GEN-LAST:event_cboSearchCriteriaActionPerformed

    private void cboRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRoutesActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cboRoutesActionPerformed
    
    private void populateRoute(){
        cboRoutes.removeAllItems();
        for(Line l : enterprise.getLineCatalog().getLinesList()){
        for(Segment seg: l.getSegments())
        {
            for(Route r : seg.getRoutes()){
//               for(RouteSchedule rs : r.getRouteSchedules()){
//                   if(rs.isSlotTaken()){
                      cboRoutes.addItem(r);
//                      break;
//                   }
//               } 
               
            }
            
        }        
     }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateSchedule;
    private javax.swing.JButton btnSearchSchedule;
    private javax.swing.JComboBox cboNewLinesSchedules;
    private javax.swing.JComboBox cboRoutes;
    private javax.swing.JComboBox cboSearchCriteria;
    private javax.swing.JComboBox cboTrains;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblSubheading;
    private javax.swing.JTable tblSearchDetails;
    // End of variables declaration//GEN-END:variables
}
