/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TMSupervisorRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.TrainAuthorityEnterprise;
import Business.Organization.Organization;
import Business.Organization.TMSupervisorOrganization;
import Business.TrainManagementSystem.Line;
import Business.TrainManagementSystem.SimulationClass;
import Business.TrainManagementSystem.Train;
import Business.TrainManagementSystem.TrainOffered;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manasi Laddha
 */
public class TMSupervisorWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TMSupervisorWorkAreaPanel
     */
    JPanel userProcessContainer;
    TMSupervisorOrganization supervisorOrganization;
    TrainAuthorityEnterprise enterprise;
    
    public TMSupervisorWorkAreaPanel(JPanel userProcessContainer,Enterprise enterprise, Organization supOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supervisorOrganization = (TMSupervisorOrganization)supOrganization;
        this.enterprise = (TrainAuthorityEnterprise) enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageStations = new javax.swing.JButton();
        btnManageLines = new javax.swing.JButton();
        btnManageTrains = new javax.swing.JButton();
        btnManageLineSchedule = new javax.swing.JButton();
        btnManageAlerts = new javax.swing.JButton();
        btnActivateLine = new javax.swing.JButton();
        btnRunningTrainStatus = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supervisor.GIF"))); // NOI18N
        jLabel1.setText("TM-Supervisor Work Area");

        btnManageStations.setBackground(new java.awt.Color(0, 0, 0));
        btnManageStations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageStations.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStations.setText("Manage Stations >>");
        btnManageStations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStationsActionPerformed(evt);
            }
        });

        btnManageLines.setBackground(new java.awt.Color(0, 0, 0));
        btnManageLines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageLines.setForeground(new java.awt.Color(255, 255, 255));
        btnManageLines.setText("Manage Lines >>");
        btnManageLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLinesActionPerformed(evt);
            }
        });

        btnManageTrains.setBackground(new java.awt.Color(0, 0, 0));
        btnManageTrains.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageTrains.setForeground(new java.awt.Color(255, 255, 255));
        btnManageTrains.setText("Manage Trains >>");
        btnManageTrains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTrainsActionPerformed(evt);
            }
        });

        btnManageLineSchedule.setBackground(new java.awt.Color(0, 0, 0));
        btnManageLineSchedule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageLineSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnManageLineSchedule.setText("Manage Line Schedules >>");
        btnManageLineSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLineScheduleActionPerformed(evt);
            }
        });

        btnManageAlerts.setBackground(new java.awt.Color(0, 0, 0));
        btnManageAlerts.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageAlerts.setForeground(new java.awt.Color(255, 255, 255));
        btnManageAlerts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alert.png"))); // NOI18N
        btnManageAlerts.setText("Manage Alerts >>");
        btnManageAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAlertsActionPerformed(evt);
            }
        });

        btnActivateLine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnActivateLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/schedule.png"))); // NOI18N
        btnActivateLine.setText("Start Activated Line");
        btnActivateLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateLineActionPerformed(evt);
            }
        });

        btnRunningTrainStatus.setBackground(new java.awt.Color(0, 0, 0));
        btnRunningTrainStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRunningTrainStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnRunningTrainStatus.setText("Running Trains Status >>");
        btnRunningTrainStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunningTrainStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(btnActivateLine, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageLineSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageStations, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(btnManageLines, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(btnManageTrains, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageAlerts, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(btnRunningTrainStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnActivateLine))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageStations, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageAlerts, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageLines, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRunningTrainStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnManageTrains, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnManageLineSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStationsActionPerformed
        // TODO add your handling code here:
        ManageStationJPanel manageStationJPanel = new ManageStationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageStationJPanel", manageStationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageStationsActionPerformed

    private void btnManageLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLinesActionPerformed
        // TODO add your handling code here:
        ManageLinesJPanel manageLinesJPanel = new ManageLinesJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageLinesJPanel", manageLinesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageLinesActionPerformed

    private void btnManageTrainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTrainsActionPerformed
        // TODO add your handling code here:
        ManageTrainsJPanel manageTrainJPanel = new ManageTrainsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageTrainsJPanel", manageTrainJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTrainsActionPerformed

    private void btnManageLineScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLineScheduleActionPerformed
        // TODO add your handling code here:
        ManageLineScheduleJPanel manageLinesJPanel = new ManageLineScheduleJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageLineScheduleJPanel", manageLinesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnManageLineScheduleActionPerformed

    private void btnManageAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAlertsActionPerformed
        // TODO add your handling code here:
        
        ManageAlertsJPanel manageAlertsJPanel = new ManageAlertsJPanel(userProcessContainer, enterprise);
         userProcessContainer.add("ManageAlertsJPanel", manageAlertsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnManageAlertsActionPerformed

    private void btnActivateLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateLineActionPerformed
        // TODO add your handling code here:
        SimulationClass objSimulator = new SimulationClass();
        Date today = new Date();

        for(Line l : enterprise.getLineCatalog().getLinesList()){
            if(l.isIsActive() && !l.isHasStarted()){
                for(Train t : enterprise.getTrainCatalog().getTrainsList()){
                    if(t.getLineOnTrain().getLineName().equals(l.getLineName())){
                        TrainOffered selectedTrainOffered =  enterprise.getTrainsOfferedHistory().fetchOrAddTrain(t, today);
                        objSimulator.generatePreviousCrowdedData(selectedTrainOffered);
                    }
                }
              l.setHasStarted(true);
            }
        }
        JOptionPane.showMessageDialog(this, "Lines Started successfully.", "Start Line", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActivateLineActionPerformed

    private void btnRunningTrainStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunningTrainStatusActionPerformed
        // TODO add your handling code here:
        ViewRunningTrainsJPanel viewRunningTrainsJPanel = new ViewRunningTrainsJPanel(userProcessContainer, enterprise);
         userProcessContainer.add("ViewRunningTrainsJPanel", viewRunningTrainsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRunningTrainStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivateLine;
    private javax.swing.JButton btnManageAlerts;
    private javax.swing.JButton btnManageLineSchedule;
    private javax.swing.JButton btnManageLines;
    private javax.swing.JButton btnManageStations;
    private javax.swing.JButton btnManageTrains;
    private javax.swing.JButton btnRunningTrainStatus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
